# Generated by Django 3.2.4 on 2021-10-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('parentId', models.CharField(db_column='parentId', max_length=100)),
                ('id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('v', models.IntegerField(db_column='__v')),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
    ]
