# Generated by Django 3.2.4 on 2021-10-08 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='v',
        ),
        migrations.AddField(
            model_name='category',
            name='_v',
            field=models.IntegerField(db_column='_v', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
