# Generated by Django 3.2.4 on 2021-10-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20211008_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
