# Generated by Django 3.2.4 on 2021-10-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
