# Generated by Django 3.2.4 on 2021-10-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Test01',
        ),
    ]
