# Generated by Django 3.2.4 on 2021-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopapp', '0008_auto_20211009_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(db_column='categoryName', max_length=100)),
                ('parentId', models.CharField(db_column='parentId', max_length=100)),
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('_v', models.IntegerField(db_column='_v')),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
