# Generated by Django 3.2.4 on 2021-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopapp', '0010_auto_20211009_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('parentId', models.CharField(db_column='parentId', max_length=100)),
                ('category_id', models.CharField(db_column='category_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('category_v', models.IntegerField(db_column='category_v', default=0)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
    ]
