# Generated by Django 3.2.4 on 2021-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('menus', models.CharField(db_column='menus', max_length=200, null=True)),
                ('role_id', models.CharField(db_column='role_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, null=True)),
                ('create_time', models.CharField(db_column='create_time', max_length=100, null=True)),
                ('role_v', models.CharField(db_column='role_v', default=0, max_length=100)),
            ],
            options={
                'db_table': 'Roles',
                'managed': True,
            },
        ),
    ]
