# Generated by Django 3.2.4 on 2021-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='auth_name',
            field=models.CharField(db_column='auth_name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='auth_time',
            field=models.DateTimeField(db_column='auth_time', max_length=100, null=True),
        ),
    ]
