# Generated by Django 3.2.4 on 2021-10-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_auto_20211018_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
