# Generated by Django 3.2.4 on 2021-10-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='user_id', max_length=100)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=200)),
                ('phone', models.CharField(db_column='phone', max_length=20, null=True)),
                ('email', models.CharField(db_column='email', max_length=100, null=True)),
                ('role_id', models.CharField(db_column='role_id', max_length=100)),
                ('create_time', models.DateTimeField(db_column='create_time', max_length=200, null=True)),
                ('user_v', models.CharField(db_column='user_v', default=0, max_length=20)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
