# Generated by Django 3.2.4 on 2021-10-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
