# Generated by Django 3.2.4 on 2021-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0022_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='menus',
            field=models.TextField(db_column='menus', default='/home', max_length=200),
        ),
    ]
