# Generated by Django 3.2.4 on 2021-10-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0023_alter_roles_menus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
